In [ ]:
import os
from google.colab import drive
drive.mount('/content/drive/')
'/content/drive/My Drive/Study/modelCheckpoint/____________________k46_boston_{epoch:02d}-{val_loss:.4f}.hdf5'

KeyboardInterrupt: ignored

In [10]:
import numpy as np
import pandas as pd
size=3
day=2

def split_y(seq,size,day):
    aaa=[]
    for i in range(len(seq)-size+1):
        subset = seq[i+size : i+size+day,0].astype('float32')
        aaa.append(subset)
    return np.array(aaa)

y = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(-1,1)
y_ = split_y(y,size,day)
print(y_)
print(y_.shape)
y_

[array([4., 5.], dtype=float32) array([5., 6.], dtype=float32)
 array([6., 7.], dtype=float32) array([7., 8.], dtype=float32)
 array([8., 9.], dtype=float32) array([ 9., 10.], dtype=float32)
 array([10.], dtype=float32) array([], dtype=float32)]
(8,)


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # This is added back by InteractiveShellApp.init_path()


array([array([4., 5.], dtype=float32), array([5., 6.], dtype=float32),
       array([6., 7.], dtype=float32), array([7., 8.], dtype=float32),
       array([8., 9.], dtype=float32), array([ 9., 10.], dtype=float32),
       array([10.], dtype=float32), array([], dtype=float32)],
      dtype=object)