In [14]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split,RandomizedSearchCV
# 파라미터
params = [
    {'model__n_estimators':[300,500,700,1000],"model__max_depth":[4,5,6,],"model__colsample_bytree":[0.6,0.9,1.2],"model__colsample_bylevel":[0.6,0.7,0.8,0.9]}
]

# 훈련셋 로드
df = pd.read_csv("train.csv",index_col=[0])
y = df.values[:,0]
x = df.values[:,2:].astype('float32')/255.0#.reshape(-1,28,28)
print(x.shape,y.shape)
# (2048, 28, 28) (2048,)

pca = PCA()
pca.fit(x)
cumsum = np.cumsum(pca.explained_variance_ratio_)
d = np.argmax(cumsum>0.991)+1 # 0.991 에서 d는 289=17^2
pca1 = PCA(n_components=d)
x = pca1.fit_transform(x)
# onehot = OneHotEncoder()
# y = onehot.fit_transform(y.reshape(-1,1)).toarray()
print(y)


x_train,x_val,y_train,y_val = train_test_split(x,y,test_size=0.20)
model = XGBClassifier(n_estimators = 200,learning_rate = 0.01,n_jobs=8)
# random_search = RandomizedSearchCV(xgb_classifier,params)
model.fit(x_train,y_train,eval_set = [(x_train,y_train),(x_val,y_val)],eval_metric = 'mlogloss')


(2048, 784) (2048,)
[5 0 4 ... 9 0 5]
[0]	validation_0-mlogloss:2.28636	validation_1-mlogloss:2.30023


C:\ProgramData\Anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[1]	validation_0-mlogloss:2.27052	validation_1-mlogloss:2.29766
[2]	validation_0-mlogloss:2.25497	validation_1-mlogloss:2.29535
[3]	validation_0-mlogloss:2.23958	validation_1-mlogloss:2.29282
[4]	validation_0-mlogloss:2.22478	validation_1-mlogloss:2.29048
[5]	validation_0-mlogloss:2.21012	validation_1-mlogloss:2.28804
[6]	validation_0-mlogloss:2.19571	validation_1-mlogloss:2.28599
[7]	validation_0-mlogloss:2.18146	validation_1-mlogloss:2.28362
[8]	validation_0-mlogloss:2.16735	validation_1-mlogloss:2.28179
[9]	validation_0-mlogloss:2.15366	validation_1-mlogloss:2.27987
[10]	validation_0-mlogloss:2.13964	validation_1-mlogloss:2.27830
[11]	validation_0-mlogloss:2.12596	validation_1-mlogloss:2.27680
[12]	validation_0-mlogloss:2.11251	validation_1-mlogloss:2.27514
[13]	validation_0-mlogloss:2.09935	validation_1-mlogloss:2.27339
[14]	validation_0-mlogloss:2.08617	validation_1-mlogloss:2.27167
[15]	validation_0-mlogloss:2.07331	validation_1-mlogloss:2.26980
[16]	validation_0-mlogloss:2.06043

[127]	validation_0-mlogloss:1.10634	validation_1-mlogloss:2.19155
[128]	validation_0-mlogloss:1.10059	validation_1-mlogloss:2.19098
[129]	validation_0-mlogloss:1.09478	validation_1-mlogloss:2.19064
[130]	validation_0-mlogloss:1.08903	validation_1-mlogloss:2.19015
[131]	validation_0-mlogloss:1.08336	validation_1-mlogloss:2.18945
[132]	validation_0-mlogloss:1.07775	validation_1-mlogloss:2.18838
[133]	validation_0-mlogloss:1.07223	validation_1-mlogloss:2.18795
[134]	validation_0-mlogloss:1.06679	validation_1-mlogloss:2.18705
[135]	validation_0-mlogloss:1.06122	validation_1-mlogloss:2.18673
[136]	validation_0-mlogloss:1.05577	validation_1-mlogloss:2.18581
[137]	validation_0-mlogloss:1.05059	validation_1-mlogloss:2.18513
[138]	validation_0-mlogloss:1.04484	validation_1-mlogloss:2.18457
[139]	validation_0-mlogloss:1.03962	validation_1-mlogloss:2.18351
[140]	validation_0-mlogloss:1.03398	validation_1-mlogloss:2.18317
[141]	validation_0-mlogloss:1.02870	validation_1-mlogloss:2.18202
[142]	vali

[252]	validation_0-mlogloss:0.60886	validation_1-mlogloss:2.13257
[253]	validation_0-mlogloss:0.60576	validation_1-mlogloss:2.13227
[254]	validation_0-mlogloss:0.60295	validation_1-mlogloss:2.13196
[255]	validation_0-mlogloss:0.60034	validation_1-mlogloss:2.13169
[256]	validation_0-mlogloss:0.59765	validation_1-mlogloss:2.13146
[257]	validation_0-mlogloss:0.59488	validation_1-mlogloss:2.13132
[258]	validation_0-mlogloss:0.59206	validation_1-mlogloss:2.13111
[259]	validation_0-mlogloss:0.58972	validation_1-mlogloss:2.13089
[260]	validation_0-mlogloss:0.58703	validation_1-mlogloss:2.13068
[261]	validation_0-mlogloss:0.58444	validation_1-mlogloss:2.13049
[262]	validation_0-mlogloss:0.58195	validation_1-mlogloss:2.13061
[263]	validation_0-mlogloss:0.57946	validation_1-mlogloss:2.13006
[264]	validation_0-mlogloss:0.57676	validation_1-mlogloss:2.12979
[265]	validation_0-mlogloss:0.57410	validation_1-mlogloss:2.12955
[266]	validation_0-mlogloss:0.57169	validation_1-mlogloss:2.12894
[267]	vali

[377]	validation_0-mlogloss:0.35795	validation_1-mlogloss:2.10936
[378]	validation_0-mlogloss:0.35640	validation_1-mlogloss:2.10911
[379]	validation_0-mlogloss:0.35502	validation_1-mlogloss:2.10909
[380]	validation_0-mlogloss:0.35351	validation_1-mlogloss:2.10868
[381]	validation_0-mlogloss:0.35208	validation_1-mlogloss:2.10843
[382]	validation_0-mlogloss:0.35066	validation_1-mlogloss:2.10828
[383]	validation_0-mlogloss:0.34930	validation_1-mlogloss:2.10820
[384]	validation_0-mlogloss:0.34794	validation_1-mlogloss:2.10803
[385]	validation_0-mlogloss:0.34662	validation_1-mlogloss:2.10804
[386]	validation_0-mlogloss:0.34516	validation_1-mlogloss:2.10794
[387]	validation_0-mlogloss:0.34387	validation_1-mlogloss:2.10785
[388]	validation_0-mlogloss:0.34242	validation_1-mlogloss:2.10780
[389]	validation_0-mlogloss:0.34107	validation_1-mlogloss:2.10801
[390]	validation_0-mlogloss:0.33978	validation_1-mlogloss:2.10781
[391]	validation_0-mlogloss:0.33827	validation_1-mlogloss:2.10754
[392]	vali

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.01, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=500, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [24]:
y_pred = model.predict(x_val)
y_pred

array([6, 2, 8, 7, 6, 9, 1, 1, 0, 9, 6, 2, 8, 1, 3, 2, 3, 6, 7, 6, 0, 2,
       6, 0, 3, 1, 0, 7, 0, 2, 1, 9, 1, 7, 2, 7, 5, 3, 3, 4, 8, 3, 1, 4,
       3, 1, 1, 5, 0, 3, 5, 6, 8, 5, 5, 4, 4, 6, 7, 6, 1, 0, 6, 0, 5, 1,
       2, 9, 6, 0, 1, 0, 1, 6, 8, 7, 8, 3, 8, 1, 6, 5, 4, 9, 1, 7, 7, 1,
       5, 7, 4, 6, 4, 1, 9, 9, 9, 9, 4, 4, 5, 0, 6, 9, 0, 1, 6, 4, 6, 9,
       1, 8, 6, 5, 0, 5, 6, 1, 6, 1, 4, 6, 9, 3, 7, 8, 5, 0, 5, 1, 9, 6,
       7, 6, 1, 5, 5, 4, 2, 2, 6, 2, 9, 6, 3, 1, 7, 5, 1, 7, 7, 3, 8, 2,
       4, 9, 1, 5, 9, 5, 7, 0, 8, 1, 4, 2, 3, 1, 4, 7, 2, 0, 0, 1, 1, 5,
       8, 9, 4, 1, 8, 7, 1, 3, 4, 2, 6, 6, 7, 4, 7, 7, 4, 0, 7, 5, 7, 5,
       7, 8, 7, 4, 6, 7, 3, 2, 4, 9, 9, 7, 8, 7, 3, 1, 9, 3, 0, 0, 2, 3,
       3, 1, 4, 3, 7, 1, 5, 1, 6, 5, 0, 7, 6, 0, 1, 7, 4, 5, 6, 9, 6, 5,
       1, 4, 1, 6, 1, 5, 3, 0, 4, 7, 1, 1, 1, 3, 7, 7, 7, 0, 1, 3, 2, 9,
       6, 5, 5, 9, 8, 4, 1, 3, 0, 9, 2, 6, 3, 1, 7, 4, 1, 6, 8, 7, 1, 1,
       1, 1, 8, 7, 2, 1, 2, 6, 4, 9, 1, 6, 4, 7, 4,

In [25]:
y_val

array([6, 2, 8, 6, 8, 5, 1, 1, 0, 9, 2, 6, 3, 1, 7, 6, 5, 0, 7, 0, 6, 6,
       8, 2, 7, 4, 0, 5, 6, 2, 5, 4, 8, 8, 9, 6, 1, 1, 3, 9, 9, 5, 4, 2,
       3, 2, 1, 7, 6, 8, 6, 8, 3, 4, 6, 2, 4, 2, 9, 8, 1, 0, 8, 0, 2, 4,
       6, 7, 0, 3, 6, 2, 5, 1, 6, 5, 7, 1, 1, 9, 6, 5, 7, 4, 1, 3, 9, 1,
       5, 8, 2, 5, 0, 1, 5, 9, 7, 8, 5, 4, 5, 1, 0, 3, 7, 9, 5, 3, 8, 4,
       6, 8, 3, 2, 5, 5, 2, 1, 2, 2, 4, 5, 9, 1, 7, 2, 4, 6, 3, 5, 6, 0,
       7, 0, 1, 5, 1, 3, 1, 0, 5, 3, 7, 5, 9, 1, 0, 3, 1, 3, 4, 4, 1, 7,
       1, 7, 1, 5, 7, 5, 5, 0, 8, 1, 0, 9, 6, 8, 0, 9, 3, 0, 7, 1, 6, 4,
       8, 9, 9, 4, 5, 5, 4, 4, 7, 2, 4, 5, 7, 5, 1, 3, 1, 8, 1, 3, 5, 5,
       2, 5, 2, 9, 5, 1, 8, 1, 4, 9, 5, 3, 8, 1, 3, 8, 9, 7, 4, 2, 1, 3,
       3, 3, 2, 2, 4, 1, 5, 8, 1, 8, 4, 2, 2, 5, 1, 7, 4, 5, 2, 5, 8, 2,
       3, 4, 1, 6, 2, 5, 3, 2, 4, 7, 3, 7, 5, 3, 9, 8, 3, 2, 3, 9, 2, 0,
       3, 6, 4, 9, 5, 8, 5, 0, 0, 3, 0, 8, 8, 2, 2, 2, 2, 6, 2, 4, 0, 7,
       1, 3, 8, 7, 6, 2, 3, 2, 0, 0, 1, 4, 4, 1, 4,

In [22]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_val,y_pred)
print("acc : ",acc)

ValueError: unknown is not supported

In [28]:

df = pd.read_csv("test.csv",index_col=[0])
x_test = df.values[:,1:].astype('float32')/255.0
x_test = pca1.transform(x_test)
y_pred = model.predict(x_test)
y_pred

array([1, 3, 3, ..., 6, 4, 5], dtype=object)

In [29]:
df_sub = pd.read_csv('submission.csv',index_col=0)
df_sub['digit'] = y_pred
df_sub.to_csv('test_2.csv')