In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Conv2D,MaxPooling2D,BatchNormalization,Flatten,Dropout,Input,Activation,Dense
from tensorflow.keras.models import Sequential,Model,load_model
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint
from sklearn.model_selection import train_test_split

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Conv2D,MaxPooling2D,BatchNormalization,Flatten,Dropout,Input,Activation,Dense
from tensorflow.keras.models import Sequential,Model,load_model
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint
from sklearn.model_selection import train_test_split

for k in range(0,10):
    df = pd.read_csv("train.csv",index_col=[0])
    modelpath = './binary_models/{}_binary.h5'.format(k)
    es = EarlyStopping(monitor='val_loss',patience=50)
    cp = ModelCheckpoint(monitor = 'val_loss',filepath=modelpath)
    
    label = df['digit']==k
    label = label.values.astype('float32')
    df['Label']=label
    x = df.values[:,2:-1].astype('float32')/255.0
    y = df.values[:,-1].astype('float32')
    # print(df)
    x_train,x_val,y_train,y_val = train_test_split(x,y,test_size=0.10,stratify=y)
    # print(x_train.shape,x_val.shape,y_train.shape,y_val.shape)
    # print(type(x_train),type(x_val),type(y_train),type(y_val))
    x_train = x_train.reshape(-1,28,28,1)#[:,2:26,2:26,:]
    x_val = x_val.reshape(-1,28,28,1)#[:,2:26,2:26,:]
    model = modeling_binary()
    model.compile(loss = 'binary_crossentropy',optimizer = 'adam',metrics=['accuracy'])
    model.fit(x_train,y_train,validation_data = (x_val,y_val),epochs=200,callbacks=[cp,es],batch_size=4)

# y = df.values[:,0]
# x = df.values[:,2:].astype('float32')/255.0#.reshape(-1,28,28)
# print(x.shape,y.shape)

Epoch 1/200
461/461 [==============================] - 5s 11ms/step - loss: 13.0770 - accuracy: 0.8519 - val_loss: 1.2113 - val_accuracy: 0.9073
Epoch 2/200
461/461 [==============================] - 4s 10ms/step - loss: 0.2866 - accuracy: 0.9148 - val_loss: 0.2759 - val_accuracy: 0.9268
Epoch 3/200
461/461 [==============================] - 4s 10ms/step - loss: 0.1744 - accuracy: 0.9354 - val_loss: 0.2228 - val_accuracy: 0.9317
Epoch 4/200
461/461 [==============================] - 4s 10ms/step - loss: 0.3226 - accuracy: 0.9148 - val_loss: 1.7231 - val_accuracy: 0.9073
Epoch 5/200
461/461 [==============================] - 4s 10ms/step - loss: 0.4893 - accuracy: 0.9072 - val_loss: 0.3183 - val_accuracy: 0.9268
Epoch 6/200
461/461 [==============================] - 4s 10ms/step - loss: 0.3154 - accuracy: 0.9181 - val_loss: 0.6684 - val_accuracy: 0.8976
Epoch 7/200
461/461 [==============================] - 4s 10ms/step - loss: 0.4365 - accuracy: 0.9164 - val_loss: 0.5127 - val_accuracy

461/461 [==============================] - 5s 10ms/step - loss: 0.0186 - accuracy: 0.9957 - val_loss: 0.2800 - val_accuracy: 0.9805
Epoch 46/200
461/461 [==============================] - 4s 10ms/step - loss: 0.2385 - accuracy: 0.9832 - val_loss: 0.3737 - val_accuracy: 0.9707
Epoch 47/200
461/461 [==============================] - 5s 10ms/step - loss: 0.1575 - accuracy: 0.9870 - val_loss: 0.2024 - val_accuracy: 0.9805
Epoch 48/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0538 - accuracy: 0.9929 - val_loss: 0.2246 - val_accuracy: 0.9805
Epoch 49/200
461/461 [==============================] - 4s 10ms/step - loss: 0.0220 - accuracy: 0.9967 - val_loss: 0.3087 - val_accuracy: 0.9805
Epoch 50/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0232 - accuracy: 0.9957 - val_loss: 0.3547 - val_accuracy: 0.9756
Epoch 51/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0159 - accuracy: 0.9973 - val_loss: 0.2557 - val_accuracy: 0.980

461/461 [==============================] - 4s 10ms/step - loss: 6.5530e-06 - accuracy: 1.0000 - val_loss: 0.4632 - val_accuracy: 0.9610
Epoch 1/200
461/461 [==============================] - 5s 10ms/step - loss: 11.2045 - accuracy: 0.8459 - val_loss: 0.7722 - val_accuracy: 0.8976
Epoch 2/200
461/461 [==============================] - 4s 10ms/step - loss: 0.3385 - accuracy: 0.8920 - val_loss: 0.2386 - val_accuracy: 0.8976
Epoch 3/200
461/461 [==============================] - 4s 10ms/step - loss: 0.2681 - accuracy: 0.8980 - val_loss: 0.2413 - val_accuracy: 0.9024
Epoch 4/200
461/461 [==============================] - 4s 10ms/step - loss: 0.5114 - accuracy: 0.8741 - val_loss: 0.3462 - val_accuracy: 0.8780
Epoch 5/200
461/461 [==============================] - 4s 10ms/step - loss: 0.2465 - accuracy: 0.9045 - val_loss: 0.2582 - val_accuracy: 0.9122
Epoch 6/200
461/461 [==============================] - 4s 10ms/step - loss: 0.3394 - accuracy: 0.8937 - val_loss: 0.3433 - val_accuracy: 0.8537

461/461 [==============================] - 4s 10ms/step - loss: 0.0731 - accuracy: 0.9897 - val_loss: 0.8398 - val_accuracy: 0.9659
Epoch 47/200
461/461 [==============================] - 4s 10ms/step - loss: 0.1498 - accuracy: 0.9848 - val_loss: 0.4645 - val_accuracy: 0.9659
Epoch 48/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0551 - accuracy: 0.9924 - val_loss: 0.8304 - val_accuracy: 0.9415
Epoch 49/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0973 - accuracy: 0.9924 - val_loss: 0.7631 - val_accuracy: 0.9463
Epoch 50/200
461/461 [==============================] - 5s 10ms/step - loss: 0.1022 - accuracy: 0.9902 - val_loss: 0.7035 - val_accuracy: 0.9610
Epoch 51/200
461/461 [==============================] - 4s 10ms/step - loss: 0.0203 - accuracy: 0.9967 - val_loss: 0.5418 - val_accuracy: 0.9610
Epoch 52/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0372 - accuracy: 0.9929 - val_loss: 0.7783 - val_accuracy: 0.941

461/461 [==============================] - 5s 10ms/step - loss: 0.4470 - accuracy: 0.8969 - val_loss: 0.5828 - val_accuracy: 0.9024
Epoch 10/200
461/461 [==============================] - 5s 10ms/step - loss: 0.3416 - accuracy: 0.9164 - val_loss: 0.3407 - val_accuracy: 0.8585
Epoch 11/200
461/461 [==============================] - 5s 10ms/step - loss: 0.2241 - accuracy: 0.9327 - val_loss: 0.5663 - val_accuracy: 0.7854
Epoch 12/200
461/461 [==============================] - 5s 10ms/step - loss: 0.2078 - accuracy: 0.9349 - val_loss: 0.3047 - val_accuracy: 0.8439
Epoch 13/200
461/461 [==============================] - 5s 10ms/step - loss: 0.2707 - accuracy: 0.9284 - val_loss: 0.2406 - val_accuracy: 0.9122
Epoch 14/200
461/461 [==============================] - 5s 10ms/step - loss: 0.3033 - accuracy: 0.9267 - val_loss: 0.1751 - val_accuracy: 0.9317
Epoch 15/200
461/461 [==============================] - 5s 10ms/step - loss: 0.1388 - accuracy: 0.9479 - val_loss: 0.1594 - val_accuracy: 0.946

461/461 [==============================] - 4s 10ms/step - loss: 0.0362 - accuracy: 0.9913 - val_loss: 0.2387 - val_accuracy: 0.9610
Epoch 48/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0186 - accuracy: 0.9984 - val_loss: 0.0736 - val_accuracy: 0.9805
Epoch 49/200
461/461 [==============================] - 4s 10ms/step - loss: 0.0070 - accuracy: 0.9989 - val_loss: 0.1159 - val_accuracy: 0.9805
Epoch 50/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0354 - accuracy: 0.9951 - val_loss: 0.7095 - val_accuracy: 0.9512
Epoch 51/200
461/461 [==============================] - 4s 10ms/step - loss: 0.0925 - accuracy: 0.9913 - val_loss: 0.1216 - val_accuracy: 0.9707
Epoch 52/200
461/461 [==============================] - 4s 10ms/step - loss: 0.0525 - accuracy: 0.9919 - val_loss: 0.4084 - val_accuracy: 0.9610
Epoch 53/200
461/461 [==============================] - 4s 10ms/step - loss: 0.0799 - accuracy: 0.9924 - val_loss: 0.2956 - val_accuracy: 0.956

461/461 [==============================] - 4s 10ms/step - loss: 0.0790 - accuracy: 0.9913 - val_loss: 1.1905 - val_accuracy: 0.9268
Epoch 62/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0751 - accuracy: 0.9935 - val_loss: 1.8850 - val_accuracy: 0.9415
Epoch 63/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0171 - accuracy: 0.9978 - val_loss: 1.7261 - val_accuracy: 0.9317
Epoch 64/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0325 - accuracy: 0.9962 - val_loss: 1.9369 - val_accuracy: 0.9366
Epoch 65/200
461/461 [==============================] - 5s 10ms/step - loss: 0.0752 - accuracy: 0.9935 - val_loss: 1.6059 - val_accuracy: 0.9415
Epoch 66/200
461/461 [==============================] - 4s 10ms/step - loss: 0.0129 - accuracy: 0.9984 - val_loss: 1.3983 - val_accuracy: 0.9415
Epoch 67/200
461/461 [==============================] - 4s 10ms/step - loss: 0.1346 - accuracy: 0.9902 - val_loss: 2.7769 - val_accuracy: 0.936

In [4]:
def modeling_binary():
    inputs = Input(shape=(28,28,1))
    x = inputs
    _x = Conv2D(256,3,padding='same')(x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    _x = Conv2D(128,3,padding='same')(_x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    x = _x
    _x = Conv2D(256,3,padding='same')(x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    _x = Conv2D(128,3,padding='same')(_x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    x = x+_x
    x = MaxPooling2D(2)(x)
    _x = Conv2D(512,3,padding='same')(x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    _x = Conv2D(128,3,padding='same')(_x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    x = x+_x
    _x = Conv2D(1024,3,padding='same')(x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    _x = Conv2D(128,3,padding='same')(_x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    x = x+_x
    x = MaxPooling2D(2)(x)
    x = Flatten()(x)
    x = Dense(1024)(x)
    x = Dense(1,activation='sigmoid')(x)
    outputs=x
    model = Model(inputs=inputs,outputs=outputs)
    return model

In [5]:
def modeling():
    inputs = Input(shape=(28,28,1))
    x = inputs
    _x = Conv2D(256,3,padding='same')(x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    _x = Conv2D(128,3,padding='same')(_x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    x = _x
    _x = Conv2D(256,3,padding='same')(x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    _x = Conv2D(128,3,padding='same')(_x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    x = x+_x
    x = MaxPooling2D(2)(x)
    _x = Conv2D(512,3,padding='same')(x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    _x = Conv2D(128,3,padding='same')(_x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    x = x+_x
    _x = Conv2D(1024,3,padding='same')(x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    _x = Conv2D(128,3,padding='same')(_x)
    _x = BatchNormalization()(_x)
    _x = Activation('relu')(_x)
    x = x+_x
    x = MaxPooling2D(2)(x)
    x = Flatten()(x)
    x = Dense(1024)(x)
    x = Dense(10,activation='softmax')(x)
    outputs=x
    model = Model(inputs=inputs,outputs=outputs)
    return model

In [2]:
def ordering(array):
    temp = array.copy()
    result = []
    for i in range(len(temp)):
        sol = np.argmax(temp)
        result.append(sol)
        temp[sol]=0
    return np.array(result)

def predict(x_test):
    temp = []
    binary_models = []
    model = load_model("02_02___.h5")
    for i in range(0,10):
        print(i)
        model = load_model('./binary_models/{}_binary.h5'.format(i))
        binary_model.append(model)
    
    for j in range(len(x_test)):
        model_sol = model.predict(j)
        binary_sol = []
        for n in range(0,10):
            result = binary_models[n].predict(j)
            binary_sol.append(result)
        binary_sol = np.array(binary_sol)
        

                
                
        

In [2]:
binary_model = []
for i in range(0,10):
    print(i)
    model = load_model('./binary_models/{}_binary.h5'.format(i))
    binary_model.append(model)



0
1
2
3
4
5
6
7
8
9


In [22]:
zxcv = binary_model[0].predict(x)
zxcv

array([[0.000000e+00],
       [1.000000e+00],
       [0.000000e+00],
       ...,
       [2.184434e-15],
       [1.000000e+00],
       [0.000000e+00]], dtype=float32)

In [4]:
df = pd.read_csv("test.csv",index_col=[0])
x = df.values[:,1:].astype('float32')/255.0
x = x.reshape(-1,28,28,1)

In [4]:
# 어레이를 줬을때 내림차순으로 가장 큰 인덱스를 저장한 리스트 반환
ary = np.array([0,0.6,0,0,0.1,0,0.3,0,0,0])
def ordering(array):
    temp = array.copy()
    result = []
    for i in range(len(temp)):
        sol = np.argmax(temp)
        result.append(sol)
        temp[sol]=0
    return np.array(result)
qwe = ordering(ary)
qwe

array([1, 6, 4, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [5]:
df_test = pd.read_csv("test.csv",index_col=[0])
x_test = df_test.values[:,1:].reshape(-1,28,28).astype('float32')/255.0
concatenate=[]
for i in range(0,10):
    concatenate.append(binary_model[i].predict(x_test))


In [6]:
ary = np.concatenate(concatenate,axis=1)
resul = np.argmax(ary,axis=-1)

In [7]:
resul

array([6, 9, 6, ..., 6, 1, 0], dtype=int64)

In [13]:
resul.shape

(2048,)

In [21]:
resul

array([5, 0, 4, ..., 9, 0, 5], dtype=int64)

In [16]:
y

NameError: name 'y' is not defined

In [15]:
df_sub = pd.read_csv('submission.csv',index_col=0)
df_sub['digit'] = resul
df_sub.to_csv('test_3.csv')

ValueError: Length of values (2048) does not match length of index (20480)

In [26]:
ary = np.round(ary,)
ary

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [27]:
for i in range(len(ary)):
    print(ary[i])
    print("\n\n\n\n\n\n")

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]







[0.   0.   0.   0.88 0.  

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]







[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[0.   0.   0.92 0.   0.   0.   0.   0.   1.   0.  ]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]







[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[0. 0

[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]







[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]







[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]







[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]







[0.   0.   0.02 0.   0.   0.   0.   0.   0.   0.  ]







[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]







[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]







[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]







[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]







[0. 1